- hosts: all

  become: true
  tasks:

    - name: stash config
      register: stash
      shell: 
        cmd: git stash
        chdir: "/root/test/office"
    - name: stash debug
      ansible.builtin.debug:
        msg: "{{stash}}"

    - name: pull
      register: out
      git:
        repo: git@git.lstar.dev:ed/lk_uo/back/office.git
        dest: /root/test/office
        accept_hostkey: yes
        key_file: /root/.ssh/playbooks
        version: lstar-develop
        update: yes
    - name: debug
      ansible.builtin.debug:
        msg: "{{out}}"
    
    - name: stash config return
      register: stashpop
      shell: 
        cmd: git stash pop
        chdir: "/root/test/office"
    - name: stash debug
      ansible.builtin.debug:
        msg: "{{stashpop}}"

    - name: maven build
      register: mav
      shell:
        cmd: mvn clean install
        chdir: "/root/test/office"
    # - name: build 
    #   register: regls
    #   shell: 
    #     cmd: docker-compose build
    #     chdir: "/root/test"
    # - name: debug-1
    #   ansible.builtin.debug:
    #     msg: "{{regls}}"
    # - name: composition up 
    #   register: regup
    #   shell: 
    #     cmd: docker-compose up -d
    #     chdir: "/root/test"
    # - name: debug-2
    #   ansible.builtin.debug:
    #     msg: "{{regup}}"