- hosts: all

  become: true
  tasks:

    - name: stash config
      register: stash
      shell: 
        cmd: git stash
        chdir: "/root/front"
    - name: stash debug
      ansible.builtin.debug:
        msg: "{{stash}}"

    - name: pull
      register: out
      git:
        repo: git@git.lstar.dev:ed/lk_uo/front.git
        dest: /root/front
        accept_hostkey: yes
        key_file: /root/.ssh/playbooks
        version: lstar-develop
        update: yes
        clone: yes 
        force: true
    - name: debug
      ansible.builtin.debug:
        msg: "{{out}}"

    - name: stash config return
      register: stashpop
      shell: 
        cmd: git stash pop
        chdir: "/root/front"
    - name: stash debug
      ansible.builtin.debug:
        msg: "{{stashpop}}"

    - name: build 
      register: regls
      shell: 
        cmd: docker-compose build
        chdir: "/root/office"
    - name: debug-1
      ansible.builtin.debug:
        msg: "{{regls}}"

    - name: composition up 
      register: regup
      shell: 
        cmd: docker-compose up -d
        chdir: "/root/office"
    - name: debug-2
      ansible.builtin.debug:
        msg: "{{regup}}"