- hosts: all

  become: true
  tasks:

    - name: stash config
      register: stash
      shell: 
        cmd: git stash
        chdir: "/root/test/front"
    - name: stash debug
      ansible.builtin.debug:
        msg: "{{stash}}"

    - name: pull
      register: out
      git:
        repo: git@git.lstar.dev:ed/lk_uo/front.git
        dest: /root/test/front
        accept_hostkey: yes
        key_file: /root/.ssh/playbooks
        version: lstar-develop
        update: yes
        clone: yes 
        force: true
    - name: debug
      ansible.builtin.debug:
        msg: "{{out}}"

    - name: stash config return
      register: stash-pop
      shell: 
        cmd: git stash pop
        chdir: "/root/test/front"
    - name: stash debug
      ansible.builtin.debug:
        msg: "{{stash-pop}}"

    - name: build 
      register: regls
      shell: 
        cmd: docker-compose build
        chdir: "/root/test"
    - name: debug-1
      ansible.builtin.debug:
        msg: "{{regls}}"
    # - name: composition up 
    #   register: regup
    #   shell: 
    #     cmd: docker-compose up -d
    #     chdir: "/root/test"
    # - name: debug-2
    #   ansible.builtin.debug:
    #     msg: "{{regup}}"