---
- hosts: all

  become: true
  tasks:
    - name: pull
      register: out
      shell: git pull 
      args:
       chdir: "/root/test/test"
       executable: /bin/bash
    - name: debug
      ansible.builtin.debug:
        msg: "{{out}}"