---
- hosts: all

  become: true
  tasks:
    - name: pull
      register: out
      git:
        repo: git@git.lstar.dev:test/test.git
        dest: /root/test
        accept_hostkey: yes
        key_file: /root/.ssh/playbooks
        update: yes
        clone: yes 
    - name: debug
      ansible.builtin.debug:
        msg: "{{out}}"
    - name: post pull
      register: regls
      shell: 
        cmd: docker-compose build
        chdir: "/root/test"
    - name: debug-1
      ansible.builtin.debug:
        msg: "{{regls}}"