---
- hosts: all

  become: true
  tasks:
    - name: pull
      register: out
      git:
        repo: "https://{{ gituser | urlencode }}:{{ gitpassword | urlencode }}@{{ gitrepotest-https | urlencode}}"
        dest: "/test"
        version: main
        update: yes
        clone: yes
    - name: debug
      ansible.builtin.debug:
        msg: "{{out}}"