---
- hosts: all

  become: true
  tasks:
    - name: pull
      register: out
      git:
        repo: "/test/test/.git"
        dest: "/test"
        version: main
        update: yes
        clone: yes
    - name: debug
      ansible.builtin.debug:
        msg: "{{out}}"