---
- hosts: all

  become: true
  tasks:
    - name: pull
      register: out
      git:
        repo: "/root/test/test/.git"
        dest: "/root/test"
        version: main
        update: yes
        clone: yes
    - name: debug
      ansible.builtin.debug:
        msg: "{{out}}"