---
- hosts: all

  become: true
  tasks:
    - name: pull
      register: out
      command: git clone "{{ gitrepotest }}" .
      args:
       chdir: "/root/test/"
       executable: /bin/bash
    - name: debug
      ansible.builtin.debug:
        msg: "{{out}}"