---
- hosts: all

  become: true
  tasks:
    - name: ls test
      register: out
      shell: 
        cmd: ls
        chdir: "/root/front"
    - name: debug
      ansible.builtin.debug:
        msg: out