---
- hosts: all

  become: true
  tasks:
    - name: ls test
      register: out
      shell: 
        cmd: ls
        chdir: "/root/front"
    - name: pull
      ansible.builtin.git:
        repo: "/root/test-front/front/.git"
        dest: "/root/test-front/front"
        version: lstar-develop
        update: yes
    - name: debug
      ansible.builtin.debug:
        msg: "{{out.stdout}}"