---
- hosts: all

  become: true
  tasks:
    - name: ls test
      register: out
      shell: 
        cmd: ls
        chdir: "/root/front"
    - name: pull
      ansible.builtin.git:
        repo: git@git.lstar.dev:ed/lk_uo/front.git
        dest: /root/test-front/front
        update: yes
    - name: debug
      ansible.builtin.debug:
        msg: "{{out.stdout}}"