---
- hosts: all

  become: true
  tasks:
    - name: ls test
      shell: 
        cmd: ls
        chdir: "/root/front"
    - name: pull
      register: out
      git:
        repo: "{{ git-front }}/.git"
        dest: "{{ git-front }}"
        version: lstar-develop
        update: yes
    - name: debug
      ansible.builtin.debug:
        msg: "{{out}}"